from dataclasses import dataclass
from enum import Enum


class APASectionType(Enum):
    """Canonical APA 7 section order."""

    PRESENTATION = "presentation"
    INDEX = "index"
    INTRODUCTION = "introduction"
    BODY = "body"
    CONCLUSION = "conclusion"
    SOURCES = "sources"

    @property
    def order(self) -> int:
        return {
            "PRESENTATION": 1,
            "INDEX": 2,
            "INTRODUCTION": 3,
            "BODY": 4,
            "CONCLUSION": 5,
            "SOURCES": 6,
        }[self.name]


@dataclass(frozen=True)
class APASection:
    """
    Immutable value object.
    Represents a single drafted section of the document.

    `title` is required: both `GeminiDocumentWriterAdapter` and
    `GoogleDocsExporterAdapter` already read/write `section.title` as
    the APA heading for the section, and `PdfDocumentExporterAdapter`
    relies on it too — it's promoted here from an implicit assumption
    to an explicit field so those adapters don't blow up at runtime.
    """

    section_type: APASectionType
    title: str
    content: str  # text generated by Gemini

    def __post_init__(self) -> None:
        if not self.title.strip():
            raise ValueError(
                f"Section '{self.section_type.value}' must have a title."
            )
        if not self.content.strip():
            raise ValueError(
                f"Section '{self.section_type.value}' cannot be empty."
            )
